### ISSUE TITLE
Sobre o scroll do chat

### ISSUE THREAD

**Issue by gabriellopes00** [maikelneris/discord-clone-vuejs#3]
Cara, muito bom seu projeto... mas como eu faço pra poder manter o scroll do chat sempre na parte inferior do container das mensagens ? Pra que toda vez que eu acrescento uma mensagem eu não ter que rolar a página para baixo manualmente... (ps: estou fazendo um chat com socket.io usando esse layout)

**Comment by maikelneris** [comment]
Caaaara, desculpa a demora pra responder, foi malz... então: eu não consegui na época que eu fiz. No projeto em React da RocketSeat o cara do vídeo faz exatamente isso. Me lembro de ter procurado pra implementar em vuejs, mas não encontrei de primeira... :(
